config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'pages/about', controller: 'pages', action: 'about'
  get 'pages/contact', controller: 'pages', action: 'contact'
  resources :pages
  resources :restaurants do
    resources :reviews, except: [:show, :index]
    collection do
      get 'search'
    end
  end
  root to: 'restaurants#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/pages/_about.html.erb
<div class="breadcrumbs">
  <div class="container">
    <div class="row">
      <div class="col-lg-4 col-sm-4">
        <h1>
          <%= @page.page_name %>
        </h1>
      </div>
    </div>
  </div>
</div>
<!--breadcrumbs end-->

<!--container start-->
<div class="container">
  <div class="row">
    <div class="col-lg-5">
      <div class="about-carousel wow fadeInLeft">
        <div id="myCarousel" class="carousel slide">
          <!-- Carousel items -->
          <div class="carousel-inner">
            <div class="active item">
              <img src="<%= @restaurant_1.image_url(:search_page) %>">
              <div class="carousel-caption">
                <p>Destictive Quality</p>
              </div>
            </div>
            <div class="item">
              <img src="<%= @restaurant_2.image_url(:search_page) %>">
              <div class="carousel-caption">
                <p>Forever Delicious</p>
              </div>
            </div>
            <div class="item">
              <img src="<%= @restaurant_3.image_url(:search_page) %>">
              <div class="carousel-caption">
                <p>Always Appetizing</p>
              </div>
            </div>
          </div>
          <!-- Carousel nav -->
          <a class="carousel-control left" href="#myCarousel" data-slide="prev">
            <i class="fa fa-angle-left">
            </i>
          </a>
          <a class="carousel-control right" href="#myCarousel" data-slide="next">
            <i class="fa fa-angle-right">
            </i>
          </a>
        </div>
      </div>
    </div>
    <div class="col-lg-7 about wow fadeInRight">
      <h4><%= @page.text_1.html_safe %></h4>
    </div>
  </div>
  <div class="row">
    <div class="hiring">
      <h2 class="wow flipInX">
        <%= @page.string_1 %>
      </h2>
      <div class="col-lg-6 col-sm-6 about-hiring">
        <div class="icon-wrap ico-bg round-five wow zoomIn" data-wow-duration="1s" data-wow-delay=".1s">
          <i class="fa fa-user">
          </i>
        </div>
        <div class="content">
          <h3 class="title wow flipInX">
            <%= @page.string_2 %>
          </h3>
          <p>
            <%= @page.text_2.html_safe %>
          </p>
        </div>
      </div>
      <div class="col-lg-6 col-sm-6 about-hiring">
        <div class="icon-wrap ico-bg round-five wow zoomIn" data-wow-duration="1s" data-wow-delay=".3s">
          <i class="fa fa-user">
          </i>
        </div>
        <div class="content">
          <h3 class="title wow flipInX">
            <%= @page.string_4 %>
          </h3>
          <p>
            <%= @page.text_4.html_safe %>
          </p>
        </div>
      </div>

      <div class="col-lg-6 col-sm-6 about-hiring">
        <div class="icon-wrap ico-bg round-five wow zoomIn" data-wow-duration="1s" data-wow-delay=".5s">
          <i class="fa fa-user">
          </i>
        </div>
        <div class="content">
          <h3 class="title wow flipInX">
            <%= @page.string_6 %>
          </h3>
          <p>
            <%= @page.text_6.html_safe %>
          </p>
        </div>
      </div>
      <div class="col-lg-6 col-sm-6 about-hiring">
        <div class="icon-wrap ico-bg round-five wow zoomIn" data-wow-duration="1s" data-wow-delay=".7s">
          <i class="fa fa-user">
          </i>
        </div>
        <div class="content">
          <h3 class="title wow flipInX">
            <%= @page.string_8 %>
          </h3>
          <p>
            <%= @page.text_8.html_safe %>
          </p>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="gray-box">
  <div class="container">
    <div class="row">
      <div class="col-lg-5">

      </div>
      <div class="col-lg-7" id="skillz">
        <h3 class="skills">
          <%= @page.string_10 %>
        </h3>

        <div class="skill_bar">
          <div class="skill_bar_progress skill_one">
            <p>
              <%= @page.string_11 %>
            </p>
          </div>
        </div>

        <div class="skill_bar">
          <div class="skill_bar_progress skill_two">
            <p>
              <%= @page.string_12 %>
            </p>
          </div>
        </div>

        <div class="skill_bar">
          <div class="skill_bar_progress skill_three">
            <p>
              <%= @page.string_13 %>
            </p>
          </div>
        </div>

        <div class="skill_bar">
          <div class="skill_bar_progress skill_four">
            <p>
              <%= @page.string_14 %>
            </p>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>


<div class="container" id="tourpackages-carousel">
  <div class="row">
    <div class="profile">
      <h2><%= @page.string_15 %></h2>
      <div class="col-xs-12 col-sm-6 col-md-3">
        <%= image_tag @page.image_1_url(:pages) if @page.image_1_url(:pages).present? %>
          <div class="caption">
            <h4><%= @page.string_3 %></h4>
            <p><%= @page.text_3.html_safe %></p>
            <div class="team-social-link">
              <a href="#">
                <i class="fa fa-facebook">
                </i>
              </a>
              <a href="#">
                <i class="fa fa-twitter">
                </i>
              </a>
              <a href="#">
                <i class="fa fa-pinterest">
                </i>
              </a>
              <a href="#">
                <i class="fa fa-linkedin">
                </i>
              </a>
              <a href="#">
                <i class="fa fa-google-plus">
                </i>
              </a>
              <a href="#">
                <i class="fa fa-github">
                </i>
              </a>
            </div>
          </div>
        </div>
      </div>

      <div class="col-xs-12 col-sm-6 col-md-3">
        <%= image_tag @page.image_2_url(:pages) if @page.image_2_url(:pages).present? %>
          <div class="caption">
            <h4><%= @page.string_5 %></h4>
            <p><%= @page.text_5.html_safe %></p>
            <div class="team-social-link">
              <a href="#">
                <i class="fa fa-facebook">
                </i>
              </a>
              <a href="#">
                <i class="fa fa-twitter">
                </i>
              </a>
              <a href="#">
                <i class="fa fa-pinterest">
                </i>
              </a>
              <a href="#">
                <i class="fa fa-linkedin">
                </i>
              </a>
              <a href="#">
                <i class="fa fa-google-plus">
                </i>
              </a>
              <a href="#">
                <i class="fa fa-github">
                </i>
              </a>
          </div>
        </div>
      </div>

      <div class="col-xs-12 col-sm-6 col-md-3">
        <%= image_tag @page.image_3_url(:pages) if @page.image_3_url(:pages).present? %>
          <div class="caption">
            <h4><%= @page.string_7 %></h4>
            <p><%= @page.text_7.html_safe %></p>
            <div class="team-social-link">
              <a href="#">
                <i class="fa fa-facebook">
                </i>
              </a>
              <a href="#">
                <i class="fa fa-twitter">
                </i>
              </a>
              <a href="#">
                <i class="fa fa-pinterest">
                </i>
              </a>
              <a href="#">
                <i class="fa fa-linkedin">
                </i>
              </a>
              <a href="#">
                <i class="fa fa-google-plus">
                </i>
              </a>
              <a href="#">
                <i class="fa fa-github">
                </i>
              </a>
          </div>
        </div>
      </div>
      <div class="col-xs-12 col-sm-6 col-md-3">
        <%= image_tag @page.image_4_url(:pages) if @page.image_4_url(:pages).present? %>
          <div class="caption">
            <h4><%= @page.string_9 %></h4>
            <p><%= @page.text_9.html_safe %></p>
            <div class="team-social-link">
              <a href="#">
                <i class="fa fa-facebook">
                </i>
              </a>
              <a href="#">
                <i class="fa fa-twitter">
                </i>
              </a>
              <a href="#">
                <i class="fa fa-pinterest">
                </i>
              </a>
              <a href="#">
                <i class="fa fa-linkedin">
                </i>
              </a>
              <a href="#">
                <i class="fa fa-google-plus">
                </i>
              </a>
              <a href="#">
                <i class="fa fa-github">
                </i>
              </a>
          </div>
        </div>
      </div>
    </div>
    <!-- End row -->
    <br>
  </div>
  <!-- End container -->
</div>
<%= render "pages/about_script" %>

app/views/pages/_about_script.html.erb
<!-- js placed at the end of the document so the pages load faster -->
<!-- <script src="assets/jquery.js">
</script>
<script src="assets/bootstrap.min.js">
</script>
<script type="text/javascript" src="assets/hover-dropdown.js">
</script>
<script type="text/javascript" src="assets/bxslider/jquery.bxslider.js">
</script>
<script defer src="assets/jquery.flexslider.js">
</script>

<script src="assets/jquery.easing.min.js">
</script>
<script src="assets/link-hover.js">
</script>
<script src="assets/wow.min.js">
</script> -->


<!--common script for all pages-->
<!-- <script src="assets/common-scripts.js">
</script> -->


<script>
  $(window).scroll(function() {
    $('#skillz').each(function(){
      var imagePos = $(this).offset().top;
      var viewportheight = window.innerHeight;
      var topOfWindow = $(window).scrollTop();
      if (imagePos < topOfWindow + viewportheight) {
        $('.skill_bar').fadeIn('slow');
        $('.skill_one').animate({
          width:'<%= @page.integer_1 %>%'}, 2500);
        $('.skill_two').animate({
          width:'<%= @page.integer_2 %>%'}, 3500);
        $('.skill_three').animate({
          width:'<%= @page.integer_3 %>%'}, 4000);
        $('.skill_four').animate({
          width:'<%= @page.integer_4 %>%'}, 2800);
        $('.skill_bar_progress p').fadeIn('slow',function(){
        });
      }
    });
  });
</script>

app/views/pages/_contact.html.erb
<div class="breadcrumbs">
  <div class="container">
    <div class="row">
      <div class="col-lg-4 col-sm-4">
        <h1>
          <%= @page.page_name %>
        </h1>
      </div>
    </div>
  </div>
</div>
<!--breadcrumbs end-->
<!--container start-->
<div class="container">
  <div class="row">
    <div class="col-lg-5 col-sm-5 address">
      <section class="contact-infos">
        <h4 class="title custom-font text-black">
          <%= @page.string_1 %>
        </h4>
        <address>
          <%= @page.text_1.html_safe %>
       </address>
     </section>
     <section class="contact-infos">
      <h4 class="title custom-font text-black">
        <%= @page.string_10 %>
      </h4>
      <address>
        <%= @page.text_2.html_safe %>
      </address>
    </section>
    <section class="contact-infos">
      <h4>
        <%= @page.string_2 %>
      </h4>
      <address>
        <%= @page.text_3.html_safe %>
      </address>
    </section>
  </div>
  <div class="col-lg-7 col-sm-7 address">
    <h4>
      Drop us a line so that we can hear from you
    </h4>
    <div class="contact-form">
      <form role="form">
        <div class="form-group">
          <label for="name">Name</label>
          <input type="text" placeholder="" id="name" class="form-control">
        </div>
        <div class="form-group">
          <label for="email">Email</label>
          <input type="text" placeholder="" id="email" class="form-control">
        </div>
        <div class="form-group">
          <label for="phone">Phone</label>
          <input type="text" id="phone" class="form-control">
        </div>
        <div class="form-group">
          <label for="phone">Message</label>
          <textarea placeholder="" rows="5" class="form-control">
          </textarea>
        </div>
        <button class="btn btn-info" type="submit">Submit</button>
      </form>
    </div>
  </div>
</div>
</div>
<!--container end-->
<!--google map start-->
<div class="contact-map">
  <div id="map-canvas" style="width: 100%; height: 400px">
  </div>
</div>
<!--google map end-->
<div class="container">
  <div class="row">
    <div class='col-md-offset-2 col-md-8 text-center'>
      <h2>
        <%= @page.string_3 %>
      </h2>
    </div>
  </div>
  <div class="row">
    <div class="col-md-offset-2 col-md-8 mar-b-30">
      <div class="carousel slide" data-ride="carousel" id="quote-carousel">
        <!-- Bottom Carousel Indicators -->
        <ol class="carousel-indicators">
          <li data-target="#quote-carousel" data-slide-to="0" class="active">
          </li>
          <li data-target="#quote-carousel" data-slide-to="1">
          </li>
          <li data-target="#quote-carousel" data-slide-to="2">
          </li>
        </ol>
        <!-- Carousel Slides / Quotes -->
        <div class="carousel-inner">
          <!-- Quote 1 -->
          <div class="item active">
            <blockquote>
              <div class="row">
                <div class="col-sm-3 text-center">
                  <img class="img-circle" src="/assets/person_1.png" style="width: 100px;height:100px;" alt="">
                  <%= image_tag @page.image_1_url(:small) %>
                </div>
                <div class="col-sm-9">
                  <p>
                    <%= @page.string_4 %>
                  </p>
                  <small>
                    <%= @page.string_5 %>
                  </small>
                </div>
              </div>
            </blockquote>
          </div>
          <!-- Quote 2 -->
          <div class="item">
            <blockquote>
              <div class="row">
                <div class="col-sm-3 text-center">
                  <img class="img-circle" src="/assets/person_2.png" style="width: 100px;height:100px;" alt="">
                  <%= image_tag @page.image_2_url(:small) %>
                </div>
                <div class="col-sm-9">
                  <p>
                    <%= @page.string_6 %>
                  </p>
                  <small>
                    <%= @page.string_7 %>
                  </small>
                </div>
              </div>
            </blockquote>
          </div>
        <!-- Quote 3 -->
          <div class="item">
            <blockquote>
              <div class="row">
                <div class="col-sm-3 text-center">
                  <img class="img-circle" src="/assets/person_3.png" style="width: 100px;height:100px;" alt="">
                  <%= image_tag @page.image_3_url(:small) %>
                </div>
                <div class="col-sm-9">
                  <p>
                    <%= @page.string_8 %>
                  </p>
                  <small>
                    <%= @page.string_9 %>
                  </small>
                </div>
              </div>
            </blockquote>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


<%= render "pages/contact_script" %>

app/views/pages/_contact_script.html.erb
<script type="text/javascript" src="//maps.googleapis.com/maps/api/js?key=AIzaSyB10NINcuOfIJcaEG442XQcDraRMgqqtm0"></script>

<script>
  $(document).ready(function() {
    //Set the carousel options
    $('#quote-carousel').carousel({
      pause: true,
      interval: 4000,
    });
  });
  //google map
  window.initialize = function() {
    var myLatlng = new google.maps.LatLng(43.6484310, -79.3771660);
    var mapOptions = {
      zoom: 15,
      center: myLatlng,
      mapTypeId: google.maps.MapTypeId.ROADMAP
    }
        var map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);
    var marker = new google.maps.Marker({
      position: myLatlng,
      map: map,
      title: 'Contact'
    });
  }
  window.google.maps.event.addDomListener(window, 'load', initialize);
</script>

app/views/pages/_form_about.html.erb
<%= tinymce_assets %><%= tinymce %>
<h1>Editing <%= @page.page_name %></h1>
<%= simple_form_for(@page) do |f| %>
<%= f.button :submit %>
    <h3>Page Title</h3>
    <%= f.input :page_name, label: false %>

    <h3>Main Text Head</h3>
    <%= f.text_area :text_1, label: false, class: "tinymce" %>

    <h3>Sub Heading</h3>
    <%= f.input :string_1, label: false %>

    <h3>Sub Title 1</h3>
    <%= f.input :string_2, label: false %>

    <h3>Sub Text 1</h3>
    <%= f.text_area :text_2, label: false, class: "tinymce" %>

    <h3>Sub Title 2</h3>
    <%= f.input :string_4, label: false %>

    <h3>Sub Text 2</h3>
    <%= f.text_area :text_4, label: false, class: "tinymce" %>

    <h3>Sub Title 3</h3>
    <%= f.input :string_6, label: false %>

    <h3>Sub Text 3</h3>
    <%= f.text_area :text_6, label: false, class: "tinymce" %>

    <h3>Sub Title 4</h3>
    <%= f.input :string_8, label: false %>

    <h3>Sub Text 4</h3>
    <%= f.text_area :text_8, label: false, class: "tinymce" %>

    <h3>Slider Main Title</h3>
    <%= f.input :string_10, label: false %>

    <h3>Slider 1 Name</h3>
    <%= f.input :string_11, label: false %>

    <h3>Slider 1 Percent</h3>
    <%= f.input :integer_1, label: false %>

    <h3>Slider 2 Name</h3>
    <%= f.input :string_12, label: false %>

    <h3>Slider 2 Percent</h3>
    <%= f.input :integer_2, label: false %>

    <h3>Slider 3 Name</h3>
    <%= f.input :string_13, label: false %>

    <h3>Slider 3 Percent</h3>
    <%= f.input :integer_3, label: false %>

    <h3>Slider 4 Name</h3>
    <%= f.input :string_14, label: false %>

    <h3>Slider 4 Percent</h3>
    <%= f.input :integer_4, label: false %>

    <h3>Bottom Title</h3>
    <%= f.input :string_15, label: false %>



    <h3>Image Title 1</h3>
    <%= f.input :string_3, label: false %>

    <h3>Image Text 1</h3>
    <%= f.text_area :text_3, label: false, class: "tinymce" %>

    <h3>Image 1</h3>
    <%= f.input :image_1, as: :file,  label: false %>

    <h3>Image Title 2</h3>
    <%= f.input :string_5, label: false %>

    <h3>Image Text 2</h3>
    <%= f.text_area :text_5, label: false, class: "tinymce" %>

    <h3>Image 2</h3>
    <%= f.input :image_2, as: :file,  label: false %>

    <h3>Image Title 3</h3>
    <%= f.input :string_7, label: false %>

    <h3>Image Text 3</h3>
    <%= f.text_area :text_7, label: false, class: "tinymce" %>

    <h3>Image 3</h3>
    <%= f.input :image_3, as: :file,  label: false %>

    <h3>Image Title 4</h3>
    <%= f.input :string_9, label: false %>

    <h3>Image Text 4</h3>
    <%= f.text_area :text_9, label: false, class: "tinymce" %>

    <h3>Image 4</h3>
    <%= f.input :image_4, as: :file,  label: false %>

    <%= f.button :submit %>

<% end %>
<br>

app/views/pages/_form_contact.html.erb
<%= tinymce_assets %><%= tinymce %>
 <h1>Editing <%= @page.page_name %></h1>
<%= simple_form_for(@page) do |f| %>

    <h3>Page Title</h3>
    <%= f.input :page_name %>
    <h3>Address Title</h3>
    <%= f.input :string_1, label: false %>
    <h3>Address Body</h3>
    <%= f.text_area :text_1, label: false, class: "tinymce" %>
    <h3>Hours Title</h3>
    <%= f.input :string_10, label: false  %>
    <h3>Hours Body</h3>
    <%= f.text_area :text_2, label: false, class: "tinymce" %>
    <h3>Telephone Title</h3>
    <%= f.input :string_2, label: false %>
    <h3>Telephone Body</h3>
    <%= f.text_area :text_3, label: false, class: "tinymce" %>
    <h3>Carousel Title</h3>
    <%= f.input :string_3, label: false %>
    <h3>Carousel Image 1 Quote</h3>
    <%= f.text_area :text_4, label: false, class: "tinymce" %>
    <h3>Carousel Image 1 Name</h3>
    <%= f.input :string_5, label: false %>
    <h3>Carousel Image 1 Image</h3>
    <%= f.input :image_1, as: :file, label: false %>
    <h3>Carousel Image 2 Quote</h3>
    <%= f.text_area :text_5, label: false, class: "tinymce" %>
    <h3>Carousel Image 2 Name</h3>
    <%= f.input :string_7, label: false %>
    <h3>Carousel Image 2 Image</h3>
    <%= f.input :image_2, as: :file, label: false %>
    <h3>Carousel Image 3 Quote</h3>
    <%= f.text_area :text_6, label: false, class: "tinymce" %>
    <h3>Carousel Image 3 Name</h3>
    <%= f.input :string_9, label: false %>
    <h3>Carousel Image 3 Image</h3>
    <%= f.input :image_3, as: :file, label: false %>

    <%= f.button :submit %>

<% end %>
<br>

app/views/pages/_form_index.html.erb
<%= tinymce_assets %><%= tinymce %>
<h1>Editing <%= @page.page_name %></h1>
<%= simple_form_for(@page) do |f| %>
 <%= f.button :submit %>
    <h3>Page Name</h3>
    <%= f.input :page_name, label: false %>

    <h3>Main Title</h3>
    <%= f.input :string_1, label: false %>

    <h3>Main Text</h3>
    <%= f.text_area :text_1, label: false, class: "tinymce" %>

    <h3>Main Image Title</h3>
    <%= f.input :string_2, label: false %>

    <h3>Image One Title</h3>
    <%= f.input :string_3, label: false %>

    <h3>Image One Text</h3>
    <%= f.text_area :text_2, label: false, class: "tinymce" %>

    <h3>Image One Image</h3>
    <%= f.input :image_1, as: :file, label: false %>

    <h3>Image Two Title</h3>
    <%= f.input :string_5, label: false %>

    <h3>Image Two Text</h3>
    <%= f.text_area :text_3, label: false, class: "tinymce" %>

    <h3>Image Two Image</h3>
    <%= f.input :image_2, as: :file, label: false %>

    <h3>Image Three Title</h3>
    <%= f.input :string_7, label: false %>

    <h3>Image Three Text</h3>
    <%= f.text_area :text_4, label: false, class: "tinymce" %>

    <h3>Image Three Image</h3>
    <%= f.input :image_3, as: :file, label: false %>

    <h3>Image Four Title</h3>
    <%= f.input :string_9, label: false %>

    <h3>Image Four Text</h3>
    <%= f.text_area :text_5, label: false, class: "tinymce" %>

    <h3>Image Four Image</h3>
    <%= f.input :image_4, as: :file, label: false %>

    <%= f.button :submit %>

<% end %>
<br>

app/views/pages/_index.html.erb
<div class="breadcrumbs">
  <div class="container">
    <div class="row">
      <div class="col-lg-4 col-sm-4">
        <h1>
          <%= @page.page_name %>, <%= current_user.username %>!
        </h1>
      </div>
    </div>
  </div>
</div>
<!--breadcrumbs end-->
<!-- Page Content -->
<div class="container">
  <!-- Jumbotron Header -->
  <header class="jumbotron hero-spacer">
    <h1>
      <%= @page.string_1 %>
    </h1>
    <p>
      <%= @page.text_1.html_safe %>
    </p>
    <p>
      <a class="btn btn-primary btn-large">
        Call to action!
      </a>
    </p>
  </header>
  <hr>
  <!-- Title -->
  <div class="row">
    <div class="col-lg-12">
      <h3>
       <%= @page.string_2 %>
      </h3>
    </div>
  </div>
 <!-- /.row -->
 <!-- Page Features -->
  <div class="row text-center">
    <div class="col-md-3 col-sm-6 hero-feature">
      <div class="thumbnail">
        <%= image_tag @page.image_1_url(:pages) if @page.image_1_url(:pages).present? %>
        <div class="caption">
          <h3>
            <%= @page.string_3 %>
        </h3>
        <p>
          <%= @page.text_2.html_safe %>
        </p>
      </div>
    </div>
  </div>
  <div class="col-md-3 col-sm-6 hero-feature">
    <div class="thumbnail">
      <%= image_tag @page.image_2_url(:pages) if @page.image_2_url(:pages).present? %>
      <div class="caption">
        <h3>
          <%= @page.string_5 %>
        </h3>
        <p>
          <%= @page.text_3.html_safe %>
        </p>
      </div>
    </div>
  </div>
  <div class="col-md-3 col-sm-6 hero-feature">
    <div class="thumbnail">
      <%= image_tag @page.image_3_url(:pages) if @page.image_3_url(:pages).present? %>
      <div class="caption">
        <h3>
          <%= @page.string_7 %>
        </h3>
        <p>
          <%= @page.text_4.html_safe %>
        </p>
      </div>
    </div>
  </div>
  <div class="col-md-3 col-sm-6 hero-feature">
    <div class="thumbnail">
      <%= image_tag @page.image_4_url(:pages) if @page.image_4_url(:pages).present? %>
      <div class="caption">
        <h3>
          <%= @page.string_9 %>
        </h3>
        <p>
          <%= @page.text_5.html_safe %>
        </p>
      </div>
    </div>
  </div>
</div>
<!-- /.row -->
<hr>

app/views/pages/about.html.erb
<%= render 'about' %>

app/views/pages/contact.html.erb
<%= render 'contact' %>

app/views/pages/edit.html.erb
<div class="container">
  <% if params[:id] == "1" %>
    <%= render 'form_index' %>
  <% end %>

  <% if params[:id] == "2" %>
    <%= render 'form_about' %>
  <% end %>

  <% if params[:id] == "3" %>
    <%= render 'form_contact' %>
  <% end %>
</div>

app/views/pages/index.html.erb
<%= render 'index' %>

app/views/pages/new.html.erb
<%= render 'form', page: @page %>
<%= link_to 'Back', pages_path %>

app/views/pages/show.html.erb
<div style="margin: 15px;" class="pull-right">
  <%= link_to 'Edit This Page', edit_page_path(@page),
                      class: "btn btn-info" if current_user.try(:admin?) %>
</div>
<%= render "index" if params[:id] == "1" %>
<%= render "about" if params[:id] == "2" %>
<%= render "contact" if params[:id] == "3" %>