config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'pages/about', controller: 'pages', action: 'about'
  get 'pages/contact', controller: 'pages', action: 'contact'
  resources :pages
  resources :restaurants do
    resources :reviews, except: [:show, :index]
    collection do
      get 'search'
    end
  end
  root to: 'restaurants#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews
  belongs_to :category
  validates_presence_of :name, :description, :city, :state_provence

  geocoded_by :full_address
  after_validation :geocode
  mount_uploader :image, ImageUploader

  def full_address
    [city, address1, address2, postalcode, state_provence].join(', ')
  end

  def self.query(params)
    restaurants = Restaurant.where(category_id: params[:category].to_i)

    restaurants = restaurants.where("name like ? or description like ?", "%#{params[:search]}%", "%#{params[:search]}%") if params[:search].present?
    restaurants = restaurants.near(params[:location], 25) if params[:location].present?
    restaurants
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :admin?, only: [:edit, :update, :destroy]
  before_action :set_user, only: [:index, :create, :update, :destroy]
  before_action :set_the_id, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create]

  # GET /restaurants
  # GET /restaurants.json
  def index
    # @restaurants = Restaurant.all
    # @fast_food_restaurants = Restaurant.where(category_id: 1)
    # @fast_food_search = Category.find(1)
    # @seafood_restaurants = Restaurant.where(category_id: 2)
    # @seafood_search = Category.find(2)
    # @steak_house_restaurants = Restaurant.where(category_id: 3)
    # @steak_house_search = Category.find(3)
    # @chinese_restaurants = Restaurant.where(category_id: 4)
    # @chinese_search = Category.find(4)
    # @family_restaurants = Restaurant.where(category_id: 5)
    # @family_search = Category.find(5)
    # @coffee_restaurants = Restaurant.where(category_id: 6)
    # @coffee_search = Category.find(6)

    if current_user

      @vlat = @user.latitude
      @vlon = @user.longitude

      visitor_latitude = @user.latitude
      visitor_longitude = @user.longitude

      @restaurants = Restaurant.near([visitor_latitude, visitor_longitude], 200)
      @fast_food_restaurants = Restaurant.where(category_id: 1).near([visitor_latitude, visitor_longitude], 200)
      @fast_food_search = Category.find(1)
      @seafood_restaurants = Restaurant.where(category_id: 2).near([visitor_latitude, visitor_longitude], 200)
      @seafood_search = Category.find(2)
      @steak_house_restaurants = Restaurant.where(category_id: 3).near([visitor_latitude, visitor_longitude], 200)
      @steak_house_search = Category.find(3)
      @chinese_restaurants = Restaurant.where(category_id: 4).near([visitor_latitude, visitor_longitude], 200)
      @chinese_search = Category.find(4)
      @family_restaurants = Restaurant.where(category_id: 5).near([visitor_latitude, visitor_longitude], 200)
      @family_search = Category.find(5)
      @coffee_restaurants = Restaurant.where(category_id: 6).near([visitor_latitude, visitor_longitude], 200)
      @coffee_search = Category.find(6)
    else

      # visitor_latitude = request.location.latitude
      # visitor_longitude = request.location.longitude

      visitor_latitude = 33.7489954
      visitor_longitude = -84.3879824

      @vlat = visitor_latitude
      @vlon = visitor_longitude

      @restaurants = Restaurant.near([visitor_latitude, visitor_longitude], 200)
      @fast_food_restaurants = Restaurant.where(category_id: 1).near([visitor_latitude, visitor_longitude], 200)
      @fast_food_search = Category.find(1)
      @seafood_restaurants = Restaurant.where(category_id: 2).near([visitor_latitude, visitor_longitude], 200)
      @seafood_search = Category.find(2)
      @steak_house_restaurants = Restaurant.where(category_id: 3).near([visitor_latitude, visitor_longitude], 200)
      @steak_house_search = Category.find(3)
      @chinese_restaurants = Restaurant.where(category_id: 4).near([visitor_latitude, visitor_longitude], 200)
      @chinese_search = Category.find(4)
      @family_restaurants = Restaurant.where(category_id: 5).near([visitor_latitude, visitor_longitude], 200)
      @family_search = Category.find(5)
      @coffee_restaurants = Restaurant.where(category_id: 6).near([visitor_latitude, visitor_longitude], 200)
      @coffee_search = Category.find(6)
    end
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
    @user = current_user
    @reviews = Review.where(restaurant_id: @restaurant)
    if @reviews.blank?
      @average_rating = 0
    else
      @average_rating = @reviews.average(:rating).round(2)
    end
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to @restaurant
      flash[:success] = "Great News! #{@user.username} your review has been saved."
    else
      flash[:error] = "Sorry #{@user.username}, see the errors below and resubmit"
      render :new
    end
  end

  # PATCH/PUT /restaurants/1
  # PATCH/PUT /restaurants/1.json
  def update
    if @restaurant.update(restaurant_params)
      flash[:success] = "Great News, #{@user.username}! The restaurant has been updated!"
      redirect_to @restaurant
    else
      flash[:danger] = "Sorry, #{@user.username}. The restaurant edit has some issues."
      render :edit
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    if @restaurant.destroy
      flash[:success] = "Okay then #{@user.username}. You have deleted the restaurant."
      redirect_to root_path
    else
      flash[:danger] = "Sorry #{@user.username}. There seems to be a problem with your delete request."
      render @restaurant
    end
  end

  def search_restaurant
    @restaurants = Restaurant.query(params)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def admin?
    unless current_user.try(:admin?)
      flash[:danger] = "You are not authourized to access this resource."
      redirect_to root_path
    end
  end

  def set_user
    @user = current_user
  end

  def set_the_id
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :description, :address1, :address2,
    :city, :state_provence, :postalcode, :phone, :email, :category_id, :image)
  end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/_categories.html.erb
<div class="row mar-b-50">
  <div class="col-md-12">
    <div class="text-center feature-head wow fadeInDown">
      <h1 class="">
        Welocme to Lista - The World's Finest Restaurants
      </h1>
    </div>
    <div class="feature-box">
      <div class="col-md-4 col-sm-4 text-center wow fadeInUp">
        <div class="feature-box-heading">
          <h4>
            <b>Fast Food</b>
          </h4>
        </div>
        <% @fast_food_restaurants.limit(4).each do |restaurant| %>
          <ul style="list-style: none;">
            <li><%= link_to restaurant.name, restaurant %></li>
          </ul>
        <% end %>
        <%= link_to "See All", search_restaurant_restaurants_path(category: @fast_food_search.id), class: "btn btn-info btn-xs" %>
      </div>
    </div>

    <div class="feature-box">
      <div class="col-md-4 col-sm-4 text-center wow fadeInUp">
        <div class="feature-box-heading">
          <h4>
            <b>Steak</b>
          </h4>
        </div>
        <% @steak_house_restaurants.limit(4).each do |restaurant| %>
          <ul style="list-style: none;">
            <li><%= link_to restaurant.name, restaurant %></li>
          </ul>
        <% end %>
        <%= link_to "See All", search_restaurant_restaurants_path(category: @steak_house_search.id), class: "btn btn-info btn-xs" %>
      </div>
    </div>

    <div class="feature-box">
      <div class="col-md-4 col-sm-4 text-center wow fadeInUp">
        <div class="feature-box-heading">
          <h4>
            <b>Seafood</b>
          </h4>
        </div>
        <% @seafood_restaurants.limit(4).each do |restaurant| %>
          <ul style="list-style: none;">
            <li><%= link_to restaurant.name, restaurant %></li>
          </ul>
        <% end %>
        <%= link_to "See All", search_restaurant_restaurants_path(category: @seafood_search.id), class: "btn btn-info btn-xs" %>
      </div>
    </div>
  </div>
</div>


<div class="row mar-b-50">
  <div class="col-md-12">
    <div class="text-center feature-head wow fadeInDown">
    </div>
    <div class="feature-box">
      <div class="col-md-4 col-sm-4 text-center wow fadeInUp">
        <div class="feature-box-heading">
          <h4>
            <b>Chinese</b>
          </h4>
        </div>
        <% @chinese_restaurants.limit(4).each do |restaurant| %>
          <ul style="list-style: none;">
            <li><%= link_to restaurant.name, restaurant %></li>
          </ul>
        <% end %>
        <%= link_to "See All", search_restaurant_restaurants_path(category: @chinese_search.id), class: "btn btn-info btn-xs" %>
      </div>
    </div>

    <div class="feature-box">
      <div class="col-md-4 col-sm-4 text-center wow fadeInUp">
        <div class="feature-box-heading">
          <h4>
            <b>Family</b>
          </h4>
        </div>
        <% @family_restaurants.limit(4).each do |restaurant| %>
          <ul style="list-style: none;">
            <li><%= link_to restaurant.name, restaurant %></li>
          </ul>
        <% end %>
        <%= link_to "See All", search_restaurant_restaurants_path(category: @family_search.id), class: "btn btn-info btn-xs" %>
      </div>
    </div>
    <div class="feature-box">
      <div class="col-md-4 col-sm-4 text-center wow fadeInUp">
        <div class="feature-box-heading">
          <h4>
            <b>Coffee</b>
          </h4>
        </div>
        <% @coffee_restaurants.limit(4).each do |restaurant| %>
        <ul style="list-style: none;">
          <li><%= link_to restaurant.name, restaurant %></li>
        </ul>
        <% end %>
        <%= link_to "See All", search_restaurant_restaurants_path(category: @coffee_search.id), class: "btn btn-info btn-xs" %>
      </div>
    </div>
  </div>
</div>

app/views/restaurants/_form.html.erb
<%= simple_form_for @restaurant do |form| %>
<div class="container">
  <div class="row">
    <div class="col-xs-4">
      <%= form.input :name, label: false, placeholder: "Enter The Restaurant Name" %>
    </div>
    <div class="col-xs-4">
      <%= form.select :category_id, Category.all.map{ |form| [form.name, form.id]} %>
    </div>
  </div>
  <!--new row-->
  <div class="row">
    <div class="col-xs-8">
      <%= form.input :description, label: false, placeholder: "Provide a Description" %>
    </div>
  </div>
  <!--new row-->
  <div class="row">
    <div class="col-xs-4">
      <%= form.input :address1, label: false, placeholder: "Street Address" %>
    </div>
    <div class="col-xs-4">
      <%= form.input :address2, label: false, placeholder: "Any Other Address Info" %>
    </div>
  </div>
  <!--new row-->
  <div class="row">
    <div class="col-xs-3">
      <%= form.input :city, label: false, placeholder: "City" %>
    </div>
    <div class="col-xs-3">
      <%= form.input :state_provence, label: false, placeholder: "State/Provence or Country" %>
    </div>
    <div class="col-xs-2">
      <%= form.input :postalcode, label: false, placeholder: "Zip or Postal Code" %>
    </div>
  </div>
  <!--new row-->
  <div class="row">
    <div class="col-xs-3">
      <%= form.input :phone, label: false, placeholder: "Restaurant Telephone" %>
    </div>
    <div class="col-xs-3">
      <%= form.input :email, label: false, placeholder: "Website or Email" %>
    </div>
    <div class="col-xs-3">
      <%= form.input :image, as: :file, label: "Got a Photo?" %>
    </div>

  </div>
  <!--new row-->
  <div class="row">
    <div class="col-xs-4">
     <%= form.submit class: "btn btn-warning" %>
    </div>
  </div>
</div>
<% end %>

app/views/restaurants/_search_text.html.erb
<% if params[:category] == '1' %>
  Lista Fast Food
<% end %>
<% if params[:category] == '2' %>
  Lista Seafood
<% end %>
<% if params[:category] == '3' %>
  Lista Steak
<% end %>
<% if params[:category] == '4' %>
  Lista Chinese
<% end %>
<% if params[:category] == '5' %>
  Lista Family
<% end %>
<% if params[:category] == '6' %>
  Lista Coffee
<% end %>
<br /><% if @restaurants.blank? %>
(No Results Found)
<% end %>

app/views/restaurants/edit.html.erb
<div class="container">
  <% if params[:id] == "1" %>
    <%= render 'form_index' %>
  <% end %>
  <% if params[:id] == "2" %>
    <%= render 'form_about' %>
  <% end %>
  <% if params[:id] == "3" %>
    <%= render 'form_contact' %>
  <% end %>
</div>

app/views/restaurants/index.html.erb
<div class="breadcrumbs">
  <div class="container">
    <div class="row">
      <div class="col-lg-4 col-sm-4">
        <h1>
          Lista Restaurants
        </h1>
      </div>
      <div class="col-lg-8 col-sm-8">
        <ol class="breadcrumb pull-right">
          <li>
            <%= link_to "Add A Restaurant", new_restaurant_path %>
          </li>
        </ol>
      </div>
    </div>
  </div>
</div>

<div class='container'>
  <div class="row">
    <div class="col-md-9">
      <%= render "restaurants/slider" %>
    </div>
    <div class="col-md-3 form-group">
      <h3>Search Lista<br /><small> For The Best Places To Eat!</small></h3><hr>
      <%= form_tag search_restaurant_restaurants_path, method: :get do |f| %>
      <div style="padding-bottom: 10px;">
        <%= text_field_tag :search, nil, placeholder: "What do you wanna eat?", class: "form-control" %>
      </div>
      <div style="padding-bottom: 10px;">
        <%= text_field_tag :location, nil, placeholder: "What city?", class: "form-control" %>
      </div>
      <%= select_tag :category, options_for_select(Category.all.map{ |category| [category.name, category.id]}), class: "form-control" %>
      <br>
      <%= submit_tag 'Search', class: "btn btn-info" %>
      <% end %>
      <br>
    </div>
  </div>
  <%= render "restaurants/categories"%>
</div>

<div class="contact-map">
  <div id="map-canvas" style="width: 100%; height: 400px">
  </div>
</div>

<script type="text/javascript" src="//maps.googleapis.com/maps/api/js?key=AIzaSyB10NINcuOfIJcaEG442XQcDraRMgqqtm0"></script>


<script>
  window.initialize = function() {
    var myLatlng = new google.maps.LatLng(<%= @vlat %>,<%= @vlon %>);
    var mapOptions = {
      zoom: 10,
      center: myLatlng,
      mapTypeId: google.maps.MapTypeId.ROADMAP
    }
    var map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);
    var marker = new google.maps.Marker({
      position: myLatlng,
      map: map,
      title: 'Contact'
    }
    );
  }
  window.google.maps.event.addDomListener(window, 'load', initialize);
</script>

app/views/restaurants/new.html.erb
<div class="breadcrumbs">
  <div class="container">
    <div class="row">
      <div class="col-lg-4 col-sm-4">
        <h1>
          Create A Restaurant Page
        </h1>
      </div>
      <div class="col-lg-8 col-sm-8">
        <ol class="breadcrumb pull-right">
          <li>
            <%= link_to "Home Pages", root_path %>
          </li>
          <li>
            <%= link_to "Restaurants", restaurants_path %>
          </li>
          <li class="active">
            Create A New Restaurant
          </li>
        </ol>
      </div>
    </div>
  </div>
</div>
<%= render "form" %>

<br>

app/views/restaurants/search.html.erb
<!--http://blackrockdigital.github.io/startbootstrap-3-col-portfolio/-->
<div class="breadcrumbs">
  <div class="container">
    <div class="row">
      <div class="col-lg-4 col-sm-4">
        <h1><%= render 'restaurants/search_text'%></h1>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <% @restaurants.each do |r| %>
    <div class="col-md-3">
      <a href="#">
      <% if r.image_url.present? %>
        <%= link_to (image_tag r.image_url(:search_page)), r %>
      <% else %>
        <%= link_to (image_tag "search_page_dummy.JPG"), r %>
      <% end %>
      </a>
      <h3>
        <%= link_to r.name, r %>
      </h3>
      <ul style="list-style-type: none;">
        <li><%= r.city.titleize %>, <%= r.state_provence.upcase %></li>
        <li><%= r.email %></li>
        <li><%= r.phone %></li>
      </ul>
    </div>
    <% end %>
  </div>
</div> <!--container close-->

app/views/restaurants/search_restaurant.html.erb
<!--http://blackrockdigital.github.io/startbootstrap-3-col-portfolio/-->
<div class="breadcrumbs">
  <div class="container">
    <div class="row">
      <div class="col-lg-4 col-sm-4">
        <h1><%= render 'restaurants/search_text'%></h1>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <% @restaurants.each do |r| %>
    <div class="col-md-3">
      <a href="#">
      <% if r.image_url.present? %>
        <%= link_to (image_tag r.image_url(:search_page)), r %>
      <% else %>
        <%= link_to (image_tag "search_page_dummy.JPG"), r %>
      <% end %>
      </a>
      <h3>
        <%= link_to r.name, r %>
      </h3>
      <ul style="list-style-type: none;">
        <li><%= r.city.titleize %>, <%= r.state_provence.upcase %></li>
        <li><%= r.email %></li>
        <li><%= r.phone %></li>
      </ul>
    </div>
    <% end %>
  </div>
</div> <!--container close-->

app/views/restaurants/show.html.erb
<div class="breadcrumbs">
  <div class="container">
    <div class="row">
      <div class="col-lg-4 col-sm-4">
        <h1>
          <%= @restaurant.name %>
        </h1>
      </div>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="pf-img text-center">
        <% if @restaurant.image_url.present? %>
          <%= image_tag @restaurant.image_url(:restaurant_show) %>
        <% else %>
          <%= image_tag "restaurant_show_dummy.JPG" %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<div id="content">
  <div class="container">
    <div class="row">
      <!-- begin:article -->
      <div class="col-md-9 col-md-push-3">
        <div class="row">
          <div class="col-md-12 single-post">
            <div id="myTabContent" class="tab-content">
              <div class="tab-pane fade in active" id="detail">
                <div class="row">
                  <div class="col-md-12">
                    <% if @reviews.blank? %>
                      <p>This establishment has no reviews. Be the first to share your dining experience!</p>
                    <% else %>
                      <p>
                        <%= @restaurant.name %> has an average rating of
                        (<%= @average_rating %>) stars
                        <span class="star-rating" data-score=<%= @average_rating %>></span>
                        and has been reviewed by
                      </p>
                      <%= @reviews.count %>
                      <%= "client".pluralize @reviews.count %>
                    <% end %>
                    <h3 class="text-muted">
                      Restaurant Overview
                    </h3>
                    <hr>

                    <%= link_to "Edit", edit_restaurant_path,
                                        class: "btn btn-warning btn-sm" if current_user.try(:admin?) %>
                    <%= link_to "Delete", restaurant_path,
                                          method: :delete,
                                          data: {confirm: "Are You Really Sure?"},
                                          class: "btn btn-danger btn-sm" if current_user.try(:admin?) %>
                    <table class="table table-bordered" style="margin-top: 10px;">
                      <tr>
                        <td>
                          <strong>
                            Restaurant Name
                          </strong>
                        </td>
                        <td>
                          <%= @restaurant.name %>
                        </td>
                      </tr>
                      <tr>
                        <td>
                          <strong>
                            Website
                          </strong>
                        </td>
                        <td>
                          <%= @restaurant.email %>
                        </td>
                      </tr>
                      <tr>
                        <td>
                          <strong>
                            Address
                          </strong>
                        </td>
                        <td>
                          <%= @restaurant.address1 %>
                          <span>
                            <%= @restaurant.address2 %>
                          </span>
                        </td>
                      </tr>
                      <tr>
                        <td>
                          <strong>
                            City | State/Provence |
                            <br />
                            Postal Code
                          </strong>
                        </td>
                        <td>
                          <%= @restaurant.city.titleize %> |
                          <span>
                            <%= @restaurant.state_provence.upcase %> |
                          </span>
                          <span>
                            <%= @restaurant.postalcode %>
                          </span>
                        </td>
                      </tr>
                      <tr>
                        <td>
                          <strong>
                            Telephone
                          </strong>
                        </td>
                        <td>
                          <%= @restaurant.phone %>
                        </td>
                      </tr>
                    </table>
                    <h3>
                      More About
                      <%= @restaurant.name %>
                    </h3>
                    <p>
                      <%= @restaurant.description %>
                    </p>
                  </div>
                </div>
              </div>
              <!--google map start-->
              <div class="contact-map">
                <div id="map-canvas" style="width: 100%; height: 400px">
                </div>
              </div>
              <!--google map end-->
              <!-- break -->
              <div class="tab-pane fade" id="location">
                <div class="row">
                  <div class="col-md-12">
                    <div id="map-property">
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- end:article -->
      <!-- begin:sidebar -->
      <div class="col-md-3 col-md-pull-9 sidebar">
        <div class="widget widget-sidebar widget-white">
          <div class="widget-header">
            <h3>
              Restaurant Reviews
            </h3>
          </div>
          <!-- break -->
          <div class="widget widget-sidebar widget-white">
            <% @reviews.each do |review| %>
            <span class="star-rating" data-score=<%= review.rating %>></span><br />
            <%= review.comment %>
            <blockquote class="blockquote">
              <p class="m-b-0">
              </p>
              <footer class="blockquote-footer pull-right">
                <cite>
                  <%= review.user.username %>
                </cite>
              </footer>
            </blockquote>
            <hr>
            <% end %>
          </div>
          <%= link_to "Create Review",
          new_restaurant_review_path(@restaurant), class: "btn btn-info" %>
        </div>
        <!-- end:sidebar -->
      </div>
    </div>
  </div>
  <!-- end:content -->
  <!-- begin:blog -->
</div>

<!-- <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB10NINcuOfIJcaEG442XQcDraRMgqqtm0&v=3.exp&AMP;sensor=false">
</script> -->

<script type="text/javascript" src="//maps.googleapis.com/maps/api/js?key=AIzaSyB10NINcuOfIJcaEG442XQcDraRMgqqtm0"></script>

<script>
  $(document).ready(function() {
    //Set the carousel options
    $('.star-rating').raty({
      path: '/assets/',
      readOnly: true,
      score: function() {
        return $(this).attr('data-score');
      }
    });
    $('#quote-carousel').carousel({
      pause: true,
      interval: 4000,
    });
  });

  window.initialize = function() {
    var myLatlng = new google.maps.LatLng(<%= @restaurant.latitude %>, <%= @restaurant.longitude %>);
    var mapOptions = {
      zoom: 10,
      center: myLatlng,
      mapTypeId: google.maps.MapTypeId.ROADMAP
    }
    var map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);
    var marker = new google.maps.Marker({
      position: myLatlng,
      map: map,
      title: 'Contact'
    }
    );
  }
  window.google.maps.event.addDomListener(window, 'load', initialize);
</script>