config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'pages/about', controller: 'pages', action: 'about'
  get 'pages/contact', controller: 'pages', action: 'contact'
  resources :pages
  resources :restaurants do
    resources :reviews, except: [:show, :index]
    collection do
      get 'search'
    end
  end
  root to: 'restaurants#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <div class="row">
      <div class="col-lg-3 col-sm-3 address wow fadeInUp" data-wow-duration="2s" data-wow-delay=".1s">
        <h1>
          contact info
        </h1>
        <address>
          <p><i class="fa fa-home pr-10"></i>Address: 55 Young Street</p>
          <p><i class="fa fa-globe pr-10"></i>Toronto, Ontario </p>
          <p><i class="fa fa-mobile pr-10"></i>Mobile : (123) 456-7890 </p>
          <p><i class="fa fa-phone pr-10"></i>Phone : (123) 456-7890 </p>
          <p><i class="fa fa-envelope pr-10"></i>Email :   <a href="javascript:;">steve@chesnowitz.com</a></p>
        </address>
      </div>
      <div class="col-lg-3 col-sm-3 wow fadeInUp" data-wow-duration="2s" data-wow-delay=".3s">
        <h1>latest tweet</h1>
        <div class="tweet-box">
          <i class="fa fa-twitter"></i>
          <em>
            Please follow
            <a href="javascript:;">@example</a>
            for all future updates of us!
            <a href="javascript:;">twitter.com/acme</a>
          </em>
        </div>
        <div class="tweet-box">
          <i class="fa fa-twitter"></i>
          <em>
            Please follow
            <a href="javascript:;">@example</a>
            for all future updates of us!
            <a href="javascript:;">twitter.com/acme</a>
          </em>
        </div>
        <div class="tweet-box">
          <i class="fa fa-twitter"></i>
          <em>
            Please follow
            <a href="javascript:;">@example</a>
            for all future updates of us!
            <a href="javascript:;">twitter.com/acme</a>
          </em>
        </div>
      </div>
      <div class="col-lg-3 col-sm-3">
        <div class="page-footer wow fadeInUp" data-wow-duration="2s" data-wow-delay=".5s">
          <h1>
            Our Company
          </h1>
          <ul class="page-footer-list">
            <li>
              <i class="fa fa-angle-right"></i>
              <a href="about.html">About Us</a>
            </li>
            <li>
              <i class="fa fa-angle-right"></i>
              <a href="faq.html">Support</a>
            </li>
            <li>
              <i class="fa fa-angle-right"></i>
              <a href="service.html">Service</a>
            </li>
            <li>
              <i class="fa fa-angle-right"></i>
              <a href="privacy-policy.html">Privacy Policy</a>
            </li>
            <li>
              <i class="fa fa-angle-right"></i>
              <a href="career.html">We are Hiring</a>
            </li>
            <li>
              <i class="fa fa-angle-right"></i>
              <a href="terms.html">Term & condition</a>
            </li>
          </ul>
        </div>
      </div>
      <div class="col-lg-3 col-sm-3">
        <div class="text-footer wow fadeInUp" data-wow-duration="2s" data-wow-delay=".7s">
          <h1>
            Text Widget
          </h1>
          <p>
            This is a text widget.Lorem ipsum dolor sit amet.
            This is a text widget.Lorem ipsum dolor sit amet.
          </p>
        </div>
      </div>
    </div>
  </div>
</footer>
<!-- footer end -->
<!--small footer start -->
<footer class="footer-small">
  <div class="container">
    <div class="row">
      <div class="col-lg-6 col-sm-6 pull-right">
        <ul class="social-link-footer list-unstyled">
          <li class="wow flipInX" data-wow-duration="2s" data-wow-delay=".1s"><a href="#"><i class="fa fa-facebook"></i></a></li>
          <li class="wow flipInX" data-wow-duration="2s" data-wow-delay=".2s"><a href="#"><i class="fa fa-google-plus"></i></a></li>
          <li class="wow flipInX" data-wow-duration="2s" data-wow-delay=".3s"><a href="#"><i class="fa fa-dribbble"></i></a></li>
          <li class="wow flipInX" data-wow-duration="2s" data-wow-delay=".4s"><a href="#"><i class="fa fa-linkedin"></i></a></li>
          <li class="wow flipInX" data-wow-duration="2s" data-wow-delay=".5s"><a href="#"><i class="fa fa-twitter"></i></a></li>
          <li class="wow flipInX" data-wow-duration="2s" data-wow-delay=".6s"><a href="#"><i class="fa fa-skype"></i></a></li>
          <li class="wow flipInX" data-wow-duration="2s" data-wow-delay=".7s"><a href="#"><i class="fa fa-github"></i></a></li>
          <li class="wow flipInX" data-wow-duration="2s" data-wow-delay=".8s"><a href="#"><i class="fa fa-youtube"></i></a></li>
        </ul>
      </div>
      <div class="col-md-4">
        <div class="copyright">
          <p>  &copy; 2012 - <%= Time.now.strftime('%Y') %> <a href="https://github.com/jywei">Roy Wei</a> </p>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="head-section">
  <div class="navbar navbar-default navbar-static-top container">
    <div class="navbar-header">
      <button class="navbar-toggle" data-target=".navbar-collapse" data-toggle="collapse" type="button">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path, class: "navbar-brand" do %>
      L<span>ista</span>
      <% end %>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <%= link_to pages_path, data: { close_others: false, delay: 0,
            hover: "dropdown"} do %>
            <i class="fa fa-home"></i> Home
          <% end %>
        </li>
        <li class="dropdown">
          <%= link_to root_path, data: { close_others: false, delay: 0,
            hover: "dropdown"} do %>
            <i class="fa fa-cutlery"></i> Restaurants
          <% end %>
        </li>
        <li class="dropdown">
          <%= link_to pages_about_path, data: { close_others: false, delay: 0,
            hover: "dropdown"} do %>
            <i class="fa fa-info-circle"></i> About Us
          <% end %>
        </li>
        <li>
          <%= link_to pages_contact_path, data: { close_others: false, delay: 0,
            hover: "dropdown"} do %>
            <i class="fa fa-envelope"></i> Contact Us
          <% end %>
        </li>
        <% if current_user %>
          <li>
            <%= link_to destroy_user_session_path, data: { close_others: false, delay: 0,
              hover: "dropdown"}, method: :delete do %>
              <i class="fa fa-stop-circle-o"></i> Sign Out
            <% end %>
          </li>
          <li>
            <%= link_to edit_user_registration_path, data: { close_others: false, delay: 0,
              hover: "dropdown"} do %>
              <i class="fa fa-edit"></i> Edit My Profile
            <% end %>
          </li>
        <% else %>
          <li>
            <%= link_to new_user_session_path, data: { close_others: false, delay: 0,
              hover: "dropdown"} do %>
              <i class="fa fa-sign-in"></i> Sign In
            <% end %>
          </li>
          <li>
            <%= link_to new_user_registration_path, data: { close_others: false, delay: 0,
              hover: "dropdown"} do %>
              <i class="fa fa-registered"></i> Register
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</header>

app/views/layouts/_script.html.erb
<%= javascript_include_tag '/assets/hover-dropdown.js' %>
<%= javascript_include_tag '/assets/bootstrap.min.js' %>
<%= javascript_include_tag '/assets/wow.min.js' %>
<%= javascript_include_tag '/assets/common-scripts.js' %>
<%= javascript_include_tag '/assets/link-hover.js' %>
<%= javascript_include_tag '/assets/superfish.js' %>
<!-- <script src="assets/jquery-1.8.3.min.js">
</script>
<script src="assets/bootstrap.min.js">
</script>
<script type="text/javascript" src="assets/hover-dropdown.js">
</script>
<script defer src="assets/jquery.flexslider.js">
</script>
<script type="text/javascript" src="assets/bxslider/jquery.bxslider.js">
</script>

<script type="text/javascript" src="assets/jquery.parallax-1.1.3.js">
</script>
<script src="assets/wow.min.js">
</script>
<script src="assets/owlcarousel/owl.carousel.js">
</script>

<script src="assets/jquery.easing.min.js">
</script>
<script src="assets/link-hover.js">
</script>
<script src="assets/superfish.js">
</script> -->


<!-- <script type="text/javascript" src="assets/parallax-slider/jquery.cslider.js"></script> -->
<script type="text/javascript">
  // $(document).ready(function() {
  //   $(function() {
  //     $('#da-slider').cslider({
  //       autoplay    : true,
  //       bgincrement : 100
  //     });
  //   });
  // })
</script>



<!--common script for all pages-->
<!-- <script src="assets/common-scripts.js"></script> -->

<script type="text/javascript">
  // jQuery(document).ready(function() {
  //   $('.bxslider1').bxSlider({
  //     minSlides: 5,
  //     maxSlides: 6,
  //     slideWidth: 360,
  //     slideMargin: 2,
  //     moveSlides: 1,
  //     responsive: true,
  //     nextSelector: '#slider-next',
  //     prevSelector: '#slider-prev',
  //     nextText: 'Onward →',
  //     prevText: '← Go back'
  //   });
  // });
</script>


<script>
  // $(document).ready(function() {
  //   $('a.info').tooltip();
  //   $(window).load(function() {
  //     $('.flexslider').flexslider({
  //       animation: "slide",
  //       start: function(slider) {
  //         $('body').removeClass('loading');
  //       }
  //     });
  //   });
  //   $(document).ready(function() {
  //     $("#owl-demo").owlCarousel({
  //       items : 4
  //     });
  //   });
  //   $(document).ready(function(){
  //     $('ul.superfish').superfish();
  //   });
  //   new WOW().init();
  // })
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lista</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render "layouts/header" %>
  <%= bootstrap_flash %>
    <%= yield %>
  <%= render "layouts/footer" %>
  <%= render "layouts/script" %>

  <!-- <script type="text/javascript" src="//maps.googleapis.com/maps/api/js?key=AIzaSyB10NINcuOfIJcaEG442XQcDraRMgqqtm0"></script> -->

  </body>
</html>